// Code generated by MockGen. DO NOT EDIT.
// Source: sd/internal/domain/services (interfaces: ICuratorRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "sd/internal/domain/dto"
	entities "sd/internal/domain/entities"

	gomock "github.com/golang/mock/gomock"
)

// MockICuratorRepo is a mock of ICuratorRepo interface.
type MockICuratorRepo struct {
	ctrl     *gomock.Controller
	recorder *MockICuratorRepoMockRecorder
}

// MockICuratorRepoMockRecorder is the mock recorder for MockICuratorRepo.
type MockICuratorRepoMockRecorder struct {
	mock *MockICuratorRepo
}

// NewMockICuratorRepo creates a new mock instance.
func NewMockICuratorRepo(ctrl *gomock.Controller) *MockICuratorRepo {
	mock := &MockICuratorRepo{ctrl: ctrl}
	mock.recorder = &MockICuratorRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICuratorRepo) EXPECT() *MockICuratorRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICuratorRepo) Create(arg0 context.Context, arg1 *dto.CreateCurator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockICuratorRepoMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICuratorRepo)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockICuratorRepo) Delete(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockICuratorRepoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICuratorRepo)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockICuratorRepo) GetAll(arg0 context.Context) (entities.Curators, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].(entities.Curators)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICuratorRepoMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICuratorRepo)(nil).GetAll), arg0)
}

// GetById mocks base method.
func (m *MockICuratorRepo) GetById(arg0 context.Context, arg1 int) (*entities.Curator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(*entities.Curator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockICuratorRepoMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockICuratorRepo)(nil).GetById), arg0, arg1)
}

// Update mocks base method.
func (m *MockICuratorRepo) Update(arg0 context.Context, arg1 int, arg2 *dto.UpdateCurator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockICuratorRepoMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICuratorRepo)(nil).Update), arg0, arg1, arg2)
}
